version: '3'

services:

  # webapp:
  #   build:
  #     context: ./my_app
  #   container_name: webapp
  #   expose:
  #     - 5000
  #   ports:
  #     - 5002:5000

  prometheus:
    image: prom/prometheus
    # depends_on:
    #   - webapp
    container_name: prometheus
    volumes:
      - ./monitoring/config/prometheus/:/etc/prometheus/
#       - ./monitoring/vols/prom:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
#    volumes:
#       - ./monitoring/vols/graf:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false